export const dummySkills: SkillRecord[] = [
  {
    id: "1",
    title: "Web Search",
    slug: "web-search",
    description: "Enables agents to search the web and retrieve relevant results using a configurable search provider.",
    category: "Research",
    tags: ["search", "web", "retrieval"],
    installCommand: "claude skill install web-search",
    createdAt: "2026-04-20T10:00:00Z",
    authorClerkId: "user_abc123",
    authorEmail: "alice@example.com",
  },
  {
    id: "2",
    title: "Code Review",
    slug: "code-review",
    description: "Analyzes pull requests and diffs to provide structured feedback on code quality, security, and style.",
    category: "Development",
    tags: ["git", "review", "code quality"],
    installCommand: "claude skill install code-review",
    createdAt: "2026-04-18T09:30:00Z",
    authorClerkId: "user_def456",
    authorEmail: "bob@example.com",
  },
  {
    id: "3",
    title: "SQL Query Builder",
    slug: "sql-query-builder",
    description: "Generates and optimizes SQL queries from natural language descriptions against a provided schema.",
    category: "Database",
    tags: ["sql", "database", "query"],
    installCommand: "claude skill install sql-query-builder",
    createdAt: "2026-04-15T14:45:00Z",
    authorClerkId: "user_ghi789",
    authorEmail: "carol@example.com",
  },
  {
    id: "4",
    title: "Slack Notifier",
    slug: "slack-notifier",
    description: "Posts formatted messages and alerts to Slack channels or direct messages via webhook or API.",
    category: "Communication",
    tags: ["slack", "notifications", "messaging"],
    installCommand: "claude skill install slack-notifier",
    createdAt: "2026-04-12T08:15:00Z",
    authorClerkId: null,
    authorEmail: "dave@example.com",
  },
  {
    id: "5",
    title: "File Summarizer",
    slug: "file-summarizer",
    description: "Reads documents, PDFs, or text files and produces concise structured summaries with key takeaways.",
    category: "Productivity",
    tags: ["summarization", "documents", "pdf"],
    installCommand: "claude skill install file-summarizer",
    createdAt: "2026-04-10T16:00:00Z",
    authorClerkId: "user_jkl012",
    authorEmail: null,
  },
];
